#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

# Check if the OS is Debian and version 10 (Buster)
if [[ $(cat /etc/os-release) == *"Debian GNU/Linux 10"* ]]; then
    echo "Updating Debian Buster sources..."
    # Update sources for Debian Buster
    echo "deb http://deb.debian.org/debian buster main
deb-src http://deb.debian.org/debian buster main
deb http://security.debian.org/debian-security buster-security main
deb-src http://security.debian.org/debian-security buster-security main
deb http://deb.debian.org/debian buster-updates main
deb-src http://deb.debian.org/debian buster-updates main
deb http://deb.debian.org/debian buster-backports main
deb-src http://deb.debian.org/debian buster-backports main" > /etc/apt/sources.list

    echo "Sources updated for Debian Buster."
    # Perform updates and upgrades for Debian Buster
    apt update
    apt-get --yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
    apt-get --yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
    sed -i 's/buster/bullseye/g' /etc/apt/sources.list
    apt update
    apt-get --yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
    apt-get --yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
    sed -i 's/bullseye/bookworm/g' /etc/apt/sources.list
    apt update
    apt-get --yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
    apt-get --yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade

elif [[ $(cat /etc/os-release) == *"Debian GNU/Linux 11"* ]]; then
    # Update sources for Debian Bookworm
    echo "deb http://deb.debian.org/debian bookworm main
deb-src http://deb.debian.org/debian bookworm main
deb http://security.debian.org/debian-security bookworm-security main
deb-src http://security.debian.org/debian-security bookworm-security main
deb http://deb.debian.org/debian bookworm-updates main
deb-src http://deb.debian.org/debian bookworm-updates main
deb http://deb.debian.org/debian bookworm-backports main
deb-src http://deb.debian.org/debian bookworm-backports main" > /etc/apt/sources.list

    # Perform updates and upgrades for Debian Bookworm
    apt update
    apt-get --yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
    apt-get --yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade

elif [[ $(cat /etc/os-release) == *"Ubuntu"* ]]; then
    apt update
    apt-get --yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade

else
    echo "System Not Supported"
fi
